export const REGISTRATION_START = 'REGISTRATION_START';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_ERROR = 'REGISTRATION_ERROR';

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const LOGOUT_START = 'LOGOUT_START';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';

export const LOAD_PHOTOS_DATA: 'LOAD_PHOTOS_DATA' = 'LOAD_PHOTOS_DATA';
export const LOAD_PHOTOS_DATA_SUCCESS: 'LOAD_PHOTOS_DATA_SUCCESS' = 'LOAD_PHOTOS_DATA_SUCCESS';
export const LOAD_PHOTOS_DATA_ERROR: 'LOAD_PHOTOS_DATA_ERROR' = 'LOAD_PHOTOS_DATA_ERROR';

export const SET_PHOTOS_SEARCH_PARAM: 'SET_PHOTOS_SEARCH_PARAM' = 'SET_PHOTOS_SEARCH_PARAM';
export const UPDATE_PHOTOS_STATE: 'UPDATE_PHOTOS_STATE' = 'UPDATE_PHOTOS_STATE';

export const ADD_PHOTO_TO_FAVORITES: 'ADD_PHOTO_TO_FAVORITES' = 'ADD_PHOTO_TO_FAVORITES';